junit 6

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -9,7 +9,19 @@ pipeline{
         
         stages{
 
-              stage('Quality Gate Status Check'){
+                stage('test'){
+                                   steps {
+                                      sh './mvnw test'
+
+                               }
+                               post{
+                               always{
+                               sh 'make check || true'
+                                    junit '**/target/*.xml'
+                               }
+                               }
+                               }
+	     stage('Quality Gate Status Check'){
                   steps{
                       script{
 			      withSonarQubeEnv('sonar') {
@@ -22,20 +34,64 @@ pipeline{
 				      }
                     		}
 		    	    sh "mvn clean install"
-		  
-                 	}
-               	 }  
-              }
-             stage('test'){
-                            steps {
-                               sh './mvnw test'
 
-                        }
-                        post{
-                        always{
-                        junit '**/target/surefire-report/TEST-*.xml'
-                        }
-                        }
-                        }
-}
-}
+                 	}
+               	 }
+              }*/
+		stage("Maven Build") {
+            steps {
+                script {
+                    sh "mvn package -DskipTests=true"
+                }
+            }
+        }
+stage("Publish to Nexus Repository Manager") {
+            steps {
+                script {
+                    pom = readMavenPom file: "pom.xml";
+                    filesByGlob = findFiles(glob: "target/*.${pom.packaging}");
+                    echo "${filesByGlob[0].name} ${filesByGlob[0].path} ${filesByGlob[0].directory} ${filesByGlob[0].length} ${filesByGlob[0].lastModified}"
+                    artifactPath = filesByGlob[0].path;
+                    artifactExists = fileExists artifactPath;
+                    if(artifactExists) {
+                        echo "*** File: ${artifactPath}, group: ${pom.groupId}, packaging: ${pom.packaging}, version ${pom.version}";
+                        nexusArtifactUploader(
+                            nexusVersion: 'nexus3',
+                            protocol: 'http',
+                            nexusUrl: '192.168.2.25:8081',
+                            groupId: 'pom.com.esprit.examen',
+                            version: 'pom.1.0',
+                            repository: 'maven-releases',
+                            credentialsId: 'nexus',
+                            artifacts: [
+                                [artifactId: 'pom.tpAchatProject',
+                                classifier: '',
+                                file: artifactPath,
+                                type: pom.packaging],
+                                [artifactId: 'pom.tpAchatProject',
+                                classifier: '',
+                                file: "pom.xml",
+                                type: "pom"]
+                            ]
+                        );
+                    } else {
+                        error "*** File: ${artifactPath}, could not be found";
+                    }
+                }
+            }
+        }
+        	      stage('test'){
+                       steps {
+                          sh './mvnw test'
+
+                   }
+                   post{
+                   always{
+                   sh 'make check || true'
+                        junit '**/target/*.xml'
+                   }
+                   }
+                   }
+
+        }
+      }
